# This is a basic workflow to help you get started with Actions

name: Changelog & Version

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate Changelog and Version
        id: conventional-changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          release-count: 1
          version-file: ./.version.yml
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish Plugin
        env:
          VERSION: ${{ steps.conventional-changelog.outputs.version }}
          CHANGELOG: ${{ steps.conventional-changelog.outputs.clean_changelog }}
          INTELLIJ_MARKETPLACE_TOKEN: ${{secrets.intellij_marketplace_token}}
          MARKETPLACE_CHANNEL: eap
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: publishPlugin
          
